### ISSUE TITLE
Registration of phantom & human datasets, and ROIs.

### ISSUE THREAD

**Issue by mathieuboudreau** [rrsg2020/analysis#1]
**To-do:**

* [x] Choose tool
* [x] Create pipeline
  * Register the raw data or T1 maps?
* [ ] Quality assurance check

**Caveats:**

* Single slice datasets don't always register well
* Some images might have warping
* At least one NIST phantom dataset was acquired on the T2 slab instead of the T1 slab, and will need to be excluded

**Comment by mathieuboudreau** [comment]
Datasets: https://osf.io/ywc9g/

**Comment by jcohenadad** [comment]
@mathieuboudreau it would be much easier with the magnitude input data, which do not have noise in the background. Looking [here](https://osf.io/46nd9/), i see only t1 maps. Did people submit also the magnitude data (T1w)? If so, is there a way to retrieve them in an "easy" manner (i.e. without manually hand-picking them)?

**Comment by mathieuboudreau** [comment]
@jcohenadad haha yup - I wanted to separate the files submitted by the authors from anything else we generate in analysis. The folders have the same structure, and the files have the same prefixes. 

Most images do have magnitude data (time dimensions is the different inversion time scans), so you get your pick of which one give better contrast between the spheres and the background. A few only have real/imaginary data though I think, but that's only 1 or 2 datasets I think.

**Comment by jcohenadad** [comment]
hum... i'm trying to create an automatic script that crawls across folders, but the inconsistencies of the folder/file naming makes it difficult. E.g.:
- 20200121_matthewgrechsollars_ICL_NIST/20200121_matthewgrechsollars_ICL_NIST_Magnitude.nii.gz
- Enclosed folder: 20200227_karakuzu_polymtl_NIST/20191213_UNF/20191213_karakuzu_UNF_NIST_FS.nii.gz
- File does not match base folder name: 20200226_iveslevesque_muhc_glen_NIST/NoPowerError/20200226_iveslevesque_muhc_glen_NIST_NoPowerError.nii.gz
…
@mathieuboudreau do you suggest i drop the idea of making an automatic crawling script, and i just manually reorganize the data as i see fit, so that the registration script can properly run on the appropriate data? and if successful, i upload the organized dataset in this issue?
What i am planning to do is simply copy the 4d magnitude data in the t1maps folder

**Comment by mathieuboudreau** [comment]
Yes I agree that unfortunately all the submissions were named consistently - I tried to encourage folks to get it as close as possible but didn't push the subject much further. 

I've setup a crawling script myself for the T1 fitting pipeline using some JSON files I wrote to identify all the datasets - feel free to reuse these for your purposes if you think it would work.

Repo: https://github.com/rrsg2020/t1_fitting_pipeline

JSON files contain all the info for each grouped dataset (field + sample pairs), and you can see how I parse/use them  in the Jupyter Notebook : https://github.com/rrsg2020/t1_fitting_pipeline/blob/master/RRSG_T1_fitting.ipynb. 
* (Note that this one in particular uses MATLAB & SoS, so don't try running it unless you've followed the installation instructions listed in the README).

**Comment by mathieuboudreau** [comment]
If you want I could write that crawling script myself too - just tell me what you need it to do.

**Comment by jcohenadad** [comment]
> If you want I could write that crawling script myself too - just tell me what you need it to do.

no worries i think i found another solution that only relies on the t1maps. Stay tuned!

**Comment by jcohenadad** [comment]
@mathieuboudreau can you give me the permission to create a PR?

**Comment by mathieuboudreau** [comment]
Huh that's odd, I didn't know that GitHub didn't allow that by default for external collaborators. I looked and couldn't find that setting, so I just invited you as an organisation member for now and will explore to find this option more later.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by mathieuboudreau** [comment]
@jcohenadad I've done a little bit of progress for this issue.

* I've manually labeled the three reference points for every T1 map + a mask for the reference image, and added/uploaded these to the OSF T1 map zip files (same folder as T1 maps).
* I wrote a script that given one of my configuration files (added to the config/ folder of this repo), it 1) downloads all the datasets in the config file (i.e. all 3T NIST T1 maps, all 3T NIST raw [magnitude/phase/real/imaginary] data). It's [this file](https://github.com/rrsg2020/analysis/blob/master/make_pooled_datasets.py), which is called like `python make_pooled_datasets.py configs/3T_NIST_t1maps.json 3T_NIST_t1maps` 
  * (**python make_pooled_datasets.py CONFIG_FILE OUTPUT_FOLDER_PREFIX**)

If you clone this repo and have ANTs and FSL installed (and the requirements in the [requirements.txt](https://github.com/rrsg2020/analysis/blob/master/requirements.txt) file of this repo), then all you need to do to register the images is run the following sets of commands to register the T1 maps together:

```bash
python make_pooled_datasets.py configs/3T_NIST_t1maps.json 3T_NIST_t1maps
cd 3T_NIST_t1maps_pooled
../register_t1maps_nist.sh
```

Here's a gif created by the output of the above registration created using imagemagick with `convert -loop 0 -delay 100 *reg.jpg out.gif ` (two of the images were acquired on the wrong slice - the T2 one instead of T1, which is why they didn't register well):

![out](https://user-images.githubusercontent.com/1421029/85914198-9e6b2c00-b811-11ea-8f10-4da18fccab2e.gif)


Note that the file make_pooled_datasets.py works with the other config files too, so you can also use it to download the magnitude/phase/real/imaginary raw dataset and pool them all in one folder (e.g. `python make_pooled_datasets.py configs/3T_NIST.json 3T_NIST`). I think you mentioned in an email thread that this feature would be useful and might lead to better registration (using a different pipeline script than the one you've already written though).

**Comment by jcohenadad** [comment]
@mathieuboudreau awesome! i'll give it a try

**Comment by mathieuboudreau** [comment]
@jcohenadad Zydrunas Gimbutas from NIST shared some scripts with me that automatically generates an ROI template for the NIST phantoms (since they know the expected positions ands radiis of the spheres in a well-positionned slice). Here's an image of a mask (zeros & ones, 192x192 since that's the dimensions of our current reference):

![T1_ROI_ones_192x192](https://user-images.githubusercontent.com/1421029/87970663-6ebee500-ca9a-11ea-8031-4ff74a618506.png)

I'll share the scripts in this repo or organisation soon (or maybe convert them from MATLAB to Python), but I've also hacked with the scripts to add IDs to the spheres:

![T1_ROI_ids_192x192](https://user-images.githubusercontent.com/1421029/87970779-9ca42980-ca9a-11ea-9896-c463cc72dad0.png)

As well as reduce the radius of the spheres to avoid edge effects in the final analysis:

![T1_ROI_ids_192x192_maskedEdges](https://user-images.githubusercontent.com/1421029/87970831-b3e31700-ca9a-11ea-80c0-958f32fad87b.png)

I think this last image is what we would want registered to each T1 map (though I haven't quite decided on which radius size I'd like). I've uploaded each of the PNGs along with them in NIfTI format on OSF: https://osf.io/abfmg/

Do you think it would be fairly simple to do something like 1- register the first mask above to the reference image and then apply the same transformation to the third image, and then 2 - apply the inversion registration transformations on the third ROI mask that was done to register each magnitude images (and do nearest-neighbour resampling the ROI mask to match the dimensions of each T1 map)?

**Comment by jcohenadad** [comment]
> Do you think it would be fairly simple to do something like 1- register the first mask above to the reference image and then apply the same transformation to the third image, and then 2 - apply the inversion registration transformations on the third ROI mask that was done to register each magnitude images (and do nearest-neighbour resampling the ROI mask to match the dimensions of each T1 map)?

yup, it should be fairly straightforward-- do you want to open an issue to continue the discussion there?

**Comment by mathieuboudreau** [comment]
We can probably just open a PR and discuss there, and simply tag this issue. I'll rename this issue to include ROIs in the registration

**Comment by jcohenadad** [comment]
just for the records, the input mask to be warped to each native space is called `T1_ROI_ids_192x192_maskedEdges.nii`

**Comment by mathieuboudreau** [comment]
@jcohenadad yup, but you might (will?) need to first register and resample the full mask (`T1_ROI_ones_192x192.nii`) first to your images as well, since this is a numerically generated mask and isn't already matching any of the images.

**Comment by jcohenadad** [comment]
> @jcohenadad yup, but you might (will?) need to first register and resample the full mask (T1_ROI_ones_192x192.nii) first to your images as well, since this is a numerically generated mask and isn't already matching any of the images.

ha! i did't get that part. Makes sense. OK sure, i'll find a way. It might actually be better to try to register each site image to this mask, instead of to an arbitrary site (currently gilbert*).

**Comment by mathieuboudreau** [comment]
Oh, one other thing I thought of. It seems that the ideal numerical phantom mask is perfectly symmetrical at every 120 degree rotations, so blindly registering this to the images and then the labelled one might (?) make it such that some masks won't have matching labels for the same T1 value of the sphere. It would be nice (though not completely required if it's too time consuming to do) if we could find a way so that the labels are registered consistently with the same sphere order (e.g. T1 sphere ~2000ms = ID 1, T2 sphere ~1500ms = ID2, etc).

**Comment by jcohenadad** [comment]
> It seems that the ideal numerical phantom mask is perfectly symmetrical at every 120 degree rotations, so blindly registering this to the images and then the labelled one might (?) make it such that some masks won't have matching labels for the same T1 value of the sphere. 

i was planning to use the same strategy as the one currently implemented to register to the "gilbert" reference, i.e., create manual labels, {1, 2, 3} on the mask

**Comment by jcohenadad** [comment]
PR started https://github.com/rrsg2020/analysis/pull/10

**Comment by jcohenadad** [comment]
@mathieuboudreau i'm working on the registration stuff-- when doing the download pooled dataset as instructed [here](https://github.com/rrsg2020/analysis#download-datasets-and-pool-into-one-folder), i don't find the labels-- did you move them somewhere else?

**Comment by mathieuboudreau** [comment]
*facepalms*, sigh, yes, my bad. I fixed a few things over the weekend in the dataset YAML/JSON , and because they're all packaged together in a zipped file, accidentally forgot to copy-over the labels when I reuploaded new versions. Sorry about that, I'm fixing it ASAP (i.e. right now, but it may take an hour or two).

**Comment by jcohenadad** [comment]
ok no pb

**Comment by jcohenadad** [comment]
we should probably point to a specific version of OSF for reproducibility (instead of the "latest" which might break)

**Comment by jcohenadad** [comment]
actually no-- scrap that ^ -- because in OSF if files are deleted they are deleted for good 😓 
that's a pros for moving the files to github, but i guess you probably don't want to make this change at this point in the project?

**Comment by mathieuboudreau** [comment]
@jcohenadad It should all be fixed now. Sorry about that.

**Comment by mathieuboudreau** [comment]
> we should probably point to a specific version of OSF for reproducibility (instead of the "latest" which might break)

Yeah, if we were at the "publication" or "finished" stage, that's what I would think of doing. Pointing to a version to be able to reproduce the figures, however allowing for uploading new fixes if feedback comes in and we need to fix things to have the "best" datasets possible at all time.

For now, what I'll do is open an issue to move any "manual" objects into their own folders on OSF, so that reuploading automatically generated data (e.g. T1 maps) 1) won't overwrite things that aren't in the pipeline (like I just did to cause the problem you experienced) and 2) won't require someone manually copying over files each time (like I just did to fix the problem you experienced). i.e. have a "Labels" folder and upload them there on osf. But to not break things further, I will keep this task for after the meeting.

For now, I think I'll pass on uploading the data GitHub, but will keep an open heart to it for the future after the meeting.

**Comment by jcohenadad** [comment]
@mathieuboudreau are the labels the same, when looking at one site, I notice that there are multiple voxels for the same values:
~~~
julien-macbook:~/code/rrsg2020_analysis $ sct_label_utils -i 3T_NIST_pooled/20200121_matthewgrechsollars_ICL_NIST_Magnitude_T1map_labels_modifheader.nii.gz -display

--
Spinal Cord Toolbox (git-jca/1656-rtd-93072dea43766d6130482b3c7e64129ecc5def9c)

pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
pixdim[0] (qfac) should be 1 (default) or -1; setting qfac to 1
Position=(183,114,0) -- Value= 1.0
Position=(183,115,0) -- Value= 1.0
Position=(183,116,0) -- Value= 1.0
Position=(184,114,0) -- Value= 1.0
Position=(184,115,0) -- Value= 1.0
Position=(184,116,0) -- Value= 1.0
Position=(185,114,0) -- Value= 1.0
Position=(185,115,0) -- Value= 1.0
Position=(185,116,0) -- Value= 1.0
Position=(95,74,0) -- Value= 2.0
Position=(95,75,0) -- Value= 2.0
Position=(95,76,0) -- Value= 2.0
Position=(96,74,0) -- Value= 2.0
Position=(96,75,0) -- Value= 2.0
Position=(96,76,0) -- Value= 2.0
Position=(97,74,0) -- Value= 2.0
Position=(97,75,0) -- Value= 2.0
Position=(97,76,0) -- Value= 2.0
Position=(86,171,0) -- Value= 3.0
Position=(86,172,0) -- Value= 3.0
Position=(86,173,0) -- Value= 3.0
Position=(87,171,0) -- Value= 3.0
Position=(87,172,0) -- Value= 3.0
Position=(87,173,0) -- Value= 3.0
Position=(88,171,0) -- Value= 3.0
Position=(88,172,0) -- Value= 3.0
Position=(88,173,0) -- Value= 3.0
~~~

which does not follow the [procedure for creating the labels](https://github.com/rrsg2020/analysis/pull/2#issue-427450135).

**Comment by mathieuboudreau** [comment]
Yup, that's the way the data was always made. Odd that it's not working for you anymore. In your earlier instructions to create labels with FSLeyes, you didn't specify exactly how many points were needed in the three reference points, so I just used the default 3x3 square options for each of the three labels, which worked without any issues in your previous pipeline.

**Comment by mathieuboudreau** [comment]
I guess in your instructions, when you said

`three (coarse) labels`

I assumed that you didn't need a single voxel for each label. What did you mean by coarse?

**Comment by jcohenadad** [comment]
> I assumed that you didn't need a single voxel for each label. What did you mean by coarse?

ah, sorry about that, i meant: "(doesn't need to be exactly at the middle, but roughtly)" (i've updated the message now)

it didn't pose any issue before because all labels were 3x3, but now that i'm creating single-point label, there is a pb.

no worries-- i'll find a solution

**Comment by mathieuboudreau** [comment]
Ok! If you need me to redo labels, just give me a heads up and I'll do them (and might use that opportunity to upload them to a different folder on OSF).

**Comment by jcohenadad** [comment]
> Ok! If you need me to redo labels, just give me a heads up and I'll do them (and might use that opportunity to upload them to a different folder on OSF).

all good, i just transformed by labels as 3x3 https://github.com/rrsg2020/analysis/pull/10/commits/10b888be9c25a86cfe90dccb605c47d6ee4bd746
