### ISSUE TITLE
Inconsistent label name: 20200302_wang_MDAnderson_day1_NIST_Magnitude_labels.nii.gz

### ISSUE THREAD

**Issue by jcohenadad** [rrsg2020/analysis#7]
should be called: `20200302_wang_MDAnderson_day1_NIST_Magnitude_T1map_labels.nii.gz`

**Comment by mathieuboudreau** [comment]
Ahh woops, my bad - thanks for catching that! I just fixed it on OSF by uploading an updated *.zip file with the corrected filename.

**Comment by jcohenadad** [comment]
working now 👍 
good news: it was the only one mislabeled 😅  → that's a very low human error rate
